export const EVENT_LIST_ADD_INSTANCE_EVENT = 'EVENT_LIST_ADD_INSTANCE_EVENT';
export const EVENT_LIST_GET_INSTANCE = 'EVENT_LIST_GET_INSTANCE';
export const EVENT_LIST_REMOVE_EVENT_CASE = 'EVENT_LIST_REMOVE_EVENT_CASE';
export const EVENT_LIST_UPDATE_INSTANCE = 'EVENT_LIST_UPDATE_INSTANCE';
export const EVENT_LIST_DELETE_INSTANCE = 'EVENT_LIST_DELETE_INSTANCE';

export const CODE_EDITOR_APPEND_CODE = 'CODE_EDITOR_APPEND_CODE';
export const CODE_EDITOR_CHANGE_CODE = 'CODE_EDITOR_CHANGE_CODE';
