const Enums = {
  AnalogConnector: 'analogConnector',
  TemperatureSensor: 'temperature',
  LightSensor: 'light',
  RotarySensor: 'rotary',
  DistanceSensor: 'distance',
  Lcd: 'lcd',
  Led: 'led',
  LedRGB: 'ledRGB',
  Motor: 'motor',
  Servo: 'servo',
  ServoConnector: 'servosConnector',
  MotorConnector: 'motorsConnector',
  Button: 'button',
  Shield: 'shield',
  Relay: 'relay',
  Motion: 'motion',
  SoundSensor: 'sound',

  analogConnector: 'Conector para analógicos',
  temperature: 'Sensor de Temperatura',
  light: 'Sensor de Luz',
  rotary: 'Sensor rotatorio',
  distance: 'Sensor de distancia',
  lcd: 'Display LCD',
  led: 'Led',
  ledRGB: 'LedRGB',
  motor: 'Motor',
  servo: 'Servo',
  servosConnector: 'Conector para servo motores',
  motorsConnector: 'Conector para motores',
  button: 'Botón',
  relay: 'Relevador',
  motion: 'Sensor de Movimiento',
  sound: 'Sensor de Sonido',
};
export default Enums;
