const Enums = {
  AnalogConnector: 'analogConnector',
  TemperatureSensor: 'temperature',
  LightSensor: 'light',
  RotarySensor: 'rotary',
  DistanceSensor: 'distance',
  Lcd: 'lcd',
  Led: 'led',
  LedRGB: 'ledRGB',
  Motor: 'motor',
  Servo: 'servo',
  ServoConnector: 'servosConnector',
  MotorConnector: 'motorsConnector',
  Button: 'button',
  Shield: 'shield',
  Relay: 'relay',
  Motion: 'motion',
  SoundSensor: 'sound',

  analogConnector: 'Conector de Sensores Analógicos',
  temperature: 'Sensor de Temperatura',
  light: 'Sensor de Luz',
  rotary: 'Sensor Rotatorio',
  distance: 'Sensor de Distancia',
  lcd: 'Display LCD',
  led: 'Led',
  ledRGB: 'LEDs RGB',
  motor: 'Motor',
  servo: 'Servo',
  servosConnector: 'Controlador de Servo-motores',
  motorsConnector: 'Controlador de Motores',
  button: 'Botón',
  relay: 'Relevador',
  motion: 'Sensor de Movimiento',
  sound: 'Sensor de Sonido',

  // Categorias de Topics en MQTT
  sensors: 'Sensores',
  digitalOutputs: 'Salidas Digitales',
  digitalInputs: 'Entradas Digitales',
};
export default Enums;
